### ISSUE TITLE
Switching to php 8.1 Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by jdcoats** [thurban/plugin_weathermap#68] opened 2023-01-26 02:32 UTC
```
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - ERROR PHP DEPRECATED in Plugin 'weathermap': Implicit conversion from float 23.5 to int loses precision in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 568
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - ERROR PHP DEPRECATED in Plugin 'weathermap': Implicit conversion from float 64.5 to int loses precision in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 568
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - ERROR PHP DEPRECATED in Plugin 'weathermap': Implicit conversion from float 57.5 to int loses precision in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 568
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - ERROR PHP DEPRECATED in Plugin 'weathermap': Implicit conversion from float 57.5 to int loses precision in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 568
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - ERROR PHP DEPRECATED in Plugin 'weathermap': Implicit conversion from float 23.5 to int loses precision in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 568
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - ERROR PHP DEPRECATED in Plugin 'weathermap': Implicit conversion from float 64.5 to int loses precision in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 568
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - ERROR PHP DEPRECATED in Plugin 'weathermap': Implicit conversion from float 57.5 to int loses precision in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 568
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
2023/01/25 21:30:25 - ERROR PHP DEPRECATED in Plugin 'weathermap': Implicit conversion from float 57.5 to int loses precision in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 568
2023/01/25 21:30:25 - CMDPHP PHP ERROR Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1112]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[685]:WeatherMap->myimagestring(), /plugins/weathermap/lib/WeatherMap.class.php[568]:imagestring(), CactiErrorHandler())
```

**Comment by jdcoats** [comment] 2023-01-26 02:45
no errors with php 7.4 or 8.0 but up to 8.1 produces this.

**Comment by TheWitness** [comment] 2023-01-26 03:01
This is a duplicate of #67 and resolved in my personal repo now.  Beta3 or release.

**Comment by jdcoats** [comment] 2023-01-26 03:03
LOL should I just not use this repo at all and just use yours?

**Comment by TheWitness** [comment] 2023-01-26 03:08
Well, I'm doing pull requests right now, which is a bit of a pain.  If you want it before the next beta, just pull mine.  We are trying to dabble with other GitHub features so as to allow the team to grow.  So far, the time we all dedicated to 1.3 kind of blew up with the new year except for me and @xmacan.  A lot of people are deploying 1.2.23 right now, I'm doing 1.2.24 this weekend.

**Comment by jdcoats** [comment] 2023-01-26 03:08
switched to your repo and back to php8.1 and confirmed okay

**Closed as completed** 2023-01-28 18:20 UTC
Labels: bug, duplicate, resolved
