### ISSUE TITLE
Option to select only Traffic rrds/graphs in data-source/graph selector option

### ISSUE THREAD

**Issue by mahavirjain98** [thurban/plugin_weathermap#94] opened 2023-02-23 06:17 UTC
Unable to search for custom graphs/data-sources (e.g: memory-usage, cpu-usage, etc.) in graph/data-source selector option under node properties or link properties other than traffic graphs/data-sources.

**Comment by TheWitness** [comment] 2023-02-24 10:30
This is a duplicate of #89.  It'll likely take a few weeks as I'm having family business for next two weekends.

**Closed as completed** 2023-02-24 10:31 UTC
Labels: bug, duplicate, resolved

**Comment by TheWitness** [comment] 2023-02-24 14:25
Resolved here: https://github.com/Cacti/plugin_weathermap/commit/350b4a311f657754b40905bf7d50a8f4a7e259fe
