### ISSUE TITLE
Uncaught DivisionByZeroError Setup.php 1070

### ISSUE THREAD

**Issue by jdcoats** [thurban/plugin_weathermap#122] opened 2023-07-21 12:04 UTC
```
2023/07/21 05:16:14 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
2023/07/21 05:16:14 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2023/07/21 05:16:14 - ERROR PHP ERROR in Plugin 'weathermap': Uncaught DivisionByZeroError: Division by zero in /var/www/localhost/htdocs/cacti/plugins/weathermap/setup.php:1070 Stack trace: #0 /var/www/localhost/htdocs/cacti/lib/plugins.php(276): weathermap_poller_output(Array) #1 /var/www/localhost/htdocs/cacti/lib/plugins.php(155): api_plugin_run_plugin_hook_function('poller_output', 'weathermap', 'weathermap_poll...', Array) #2 /var/www/localhost/htdocs/cacti/lib/poller.php(812): api_plugin_hook_function('poller_output', Array) #3 /var/www/localhost/htdocs/cacti/poller.php(780): process_poller_output(Resource id #70) #4 {main} thrown in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/setup.php on line: 1070

```

**Comment by TheWitness** [comment] 2023-07-21 13:39
Duplicate of #121

**Closed as completed by TheWitness** 2023-07-21 13:39 UTC
Labels: duplicate
