### ISSUE TITLE
Weathermap getting disabled when attempting to edit a map

### ISSUE THREAD

**Issue by evilnate83** [thurban/plugin_weathermap#53] opened 2023-01-17 21:21 UTC
OS - Oracle Linux 8

Apache status
`● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/httpd.service.d
           └─php-fpm.conf
   Active: active (running) since Mon 2023-01-16 20:00:50 EST; 20h ago
     Docs: man:httpd.service(8)
 Main PID: 4188 (httpd)
   Status: "Total requests: 1633; Idle/Busy workers 100/0;Requests/sec: 0.0223; Bytes served/sec: 126 B/sec"
    Tasks: 278 (limit: 153432)
   Memory: 56.7M
   CGroup: /system.slice/httpd.service
           ├─4188 /usr/sbin/httpd -DFOREGROUND
           ├─4189 /usr/sbin/httpd -DFOREGROUND
           ├─4190 /usr/sbin/httpd -DFOREGROUND
           ├─4191 /usr/sbin/httpd -DFOREGROUND
           ├─4193 /usr/sbin/httpd -DFOREGROUND
           └─4405 /usr/sbin/httpd -DFOREGROUND

MariaDB version
`● mariadb.service - MariaDB 10.3 database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2023-01-16 19:52:37 EST; 20h ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
 Main PID: 1308 (mysqld)
   Status: "Taking your SQL requests now..."
    Tasks: 77 (limit: 153432)
   Memory: 303.5M
   CGroup: /system.slice/mariadb.service
           └─1308 /usr/libexec/mysqld --basedir=/usr
`

PHP version
`PHP 7.4.33 (cli) (built: Dec 19 2022 13:23:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
`

Errors from the cacti log
`2023-01-17 16:15:23 - ERROR PHP ERROR in  Plugin 'weathermap': Uncaught Error: Class 'index' not found in /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php:841 Stack trace: #0 /var/ww
w/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(529): WeatherMap->LoadPlugins() #1 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(372): WeatherMap->Reset() #2 /var/www/htm
l/cacti/plugins/weathermap/weathermap-cacti-plugin-editor.php(281): WeatherMap->__construct() #3 {main} thrown in file: /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 841
2023-01-17 16:15:23 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2023-01-17 16:15:23 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
`

**Comment by TheWitness** [comment] 2023-01-18 02:06
Apply this patch.  It may take a day or so to get merged.

https://github.com/Cacti/plugin_weathermap/pull/54

**Comment by netniV** [comment] 2023-01-18 12:59
This was a duplicate of #52 so closing for now.

**Closed as completed by netniV** 2023-01-18 12:59 UTC
Labels: duplicate
